[build]
  # Build command - unified build script that detects environment
  command = "node build.js"
  
  # Publish directory - the root directory since it's a static site
  publish = "."

[build.environment]
  # Node.js version for build process
  NODE_VERSION = "18"

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://maps.googleapis.com https://www.gstatic.com https://www.google.com https://cdnjs.cloudflare.com https://apis.google.com https://www.googletagmanager.com; connect-src 'self' https://maps.googleapis.com https://www.googleapis.com https://firebase.googleapis.com https://firebaseinstallations.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com; img-src 'self' data: https: blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;"

# Cache static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect root to main app
[[redirects]]
  from = "/"
  to = "/src/pages/index.html"
  status = 200

# Handle 404s by redirecting to main app
[[redirects]]
  from = "/*"
  to = "/src/pages/index.html"
  status = 404